### ISSUE TITLE
Feature rest operator

### ISSUE THREAD

**Issue by mattphillips** [wyze/eslint-plugin-wyze#18]
Hey, is there a way to use the rest operator on an object with the `wyze/sort-destructuring-keys` rule without an error/warning?

```js
const { x, y, z, ...rest } = this.props;
```

**Comment by wyze** [comment]
This should work now. What error/warning are you receiving? What parser are you using for eslint?

**Comment by mattphillips** [comment]
Hey thanks for looking at this! 😄 

The error/ warning is: 

```
[eslint] Destructuring keys should be sorted in ascending order. 'rest' should be before 'z'. (wyze/sort-destructuring-keys)
```

I'm using [babel-eslint](https://github.com/babel/babel-eslint) as my parser v7.2.3 and eslint v4.1.1

**Comment by wyze** [comment]
I'd consider this a bug, because I think that the rest operator is supposed to be the last. I just cut a new release with both fixes!

**Comment by mattphillips** [comment]
Cracking work dude thanks a lot for fixing and publishing this so quickly!
