### ISSUE TITLE
Better Property.value consumption in sort-destructuring-keys

### ISSUE THREAD

**Issue by P0lip** [wyze/eslint-plugin-wyze#20]
Hey!
First of all, thank you for sharing your plugin. Quite a few rules are really useful in daily use case.
There is a minor flaw in the current implementation of `sort-destructuring-keys` rule though, though.
Such patterns are unsupported at the moment:
```js
const props = { a: 1, b: 2 }
const { b, a = b } = props
```

```js
const props = { a: 1, B: 2 }
const { z, b = z, a = z + b } = props
```

```js
const { z, c = 10, a = z() + c } = { z: () => 2 };
```

```js
const { b, a = (c = b) => c } = { b : 2 }
```

Basically, we could take nodes with type `AssignmentPattern` into consideration.
We would just list all keys from Identifiers located in valid nodes such as `ConditionalExpression`, `BinaryExpression`, `CallExpression`, `ArrowFunctionExpression`, `FunctionExpression` etc.
Next step would be to filter these keys and pick only the ones that are found within `ObjectPattern`.
Once that is done, we could use them in sorting function.
I would be more than happy to give it a shot, since it's something I am missing and would use in my projects.
What do you think about that? Do we want to support such a case?
If so, I will proceed with actual implementation.
Cheers.

**Comment by wyze** [comment]
I'd definitely be open to supporting this. Go ahead and give it a shot in a PR!
