### ISSUE TITLE
`sort-imports` autofix incorrect with typescript-eslint-parser

### ISSUE THREAD

**Issue by justinanastos** [wyze/eslint-plugin-wyze#23]
The problem lies in what is returned in AST Nodes from `typescript-eslint-parser` when the fixer is trying to find the delimiter between declarations or specifiers when re-ordering them:

https://github.com/wyze/eslint-plugin-wyze/blob/master/lib/rules/sort-imports.js#L49-L50
https://github.com/wyze/eslint-plugin-wyze/blob/master/lib/rules/sort-imports.js#L60-L61

# How To Fix It

The typescript parser apparently does not return `start` and `end` values on the node itself, instead requiring us to use `range[0]` and `range[1]`. If I replace the above referenced lines' references to `.start` and `.end` with `.range[0]` and `.range[1]` respectively, then the issue is resolved.

# How To Fix It

I have a fix and want to figure out exactly how you'd like me to handle it. I see two options:

1. I just fix the code. Nothing changes, all tests pass.

    This provides no detectability because the tests already pass and will pass if this change is reverted, even though this won't work with typescript. If you don't use typescript, then you probably don't care :)

2. I fix the code and add a test that uses `typescript-eslint-parser`. This requires installing a `devDependency` of `typescript-eslint-parser` and it's `peerDependency` of `typescript`. I can then write a test that uses the typescript parser. I've done this in development; writing tests that fail before the above mentioned fix and pass after. All remaining tests continue to behave the same.

Let me know which you'd prefer and I'll send the PR. I'm going to optimistically assume you want version #2 and submit a PR.

# Long Version: Why This Hurts

This results in the delimiter coming back as undefined and the two declarations being merged. This manifests itself in two ways, depending if it's a declaration or a specifier:

```jsx
import B from 'b';
import A from 'a';
```

will autofix to the following:

```jsx
import A from 'a';import B from 'b';
```

That will most likely be cleaned up by another rule, not causing any real issues. If there is no semicolon `;`, then this will cause a hard failure in the resulting fixed code.

```jsx
import B from 'b'
import A from 'a'
```

will autofix to the following:

```jsx
import A from 'a'import B from 'b'
```

Second, using a specifier will cause the same issue, but will be much more insidious because it'll be removing whitespace from between to specifiers:

```jsx
import {b, a} from 'a';
```

will be fixed to:

```jsx
import {ab} from 'a';
```

**Comment by wyze** [comment]
Thanks for the detailed ticket. I, as well, prefer the 2nd option!
